
services:
  backend:
    build:
      context: ../apps/backend
      dockerfile: Dockerfile
    container_name: terminal_backend
    env_file:
      - ../apps/backend/.env
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build:
      context: ../apps/frontend
      dockerfile: Dockerfile
    container_name: terminal_frontend
    env_file:
      - ../apps/frontend/.env
    ports:
      - "5174:80"
    depends_on:
      - backend
    restart: unless-stopped
